//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeadSpringApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/HeadSpringWcf")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeJobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeePhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeRoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeEmail {
            get {
                return this.EmployeeEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeEmailField, value) != true)) {
                    this.EmployeeEmailField = value;
                    this.RaisePropertyChanged("EmployeeEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeIDField, value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeJobTitle {
            get {
                return this.EmployeeJobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeJobTitleField, value) != true)) {
                    this.EmployeeJobTitleField = value;
                    this.RaisePropertyChanged("EmployeeJobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeLocation {
            get {
                return this.EmployeeLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeLocationField, value) != true)) {
                    this.EmployeeLocationField = value;
                    this.RaisePropertyChanged("EmployeeLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeName {
            get {
                return this.EmployeeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeNameField, value) != true)) {
                    this.EmployeeNameField = value;
                    this.RaisePropertyChanged("EmployeeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeePhoneNumber {
            get {
                return this.EmployeePhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeePhoneNumberField, value) != true)) {
                    this.EmployeePhoneNumberField = value;
                    this.RaisePropertyChanged("EmployeePhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeRole {
            get {
                return this.EmployeeRoleField;
            }
            set {
                if ((this.EmployeeRoleField.Equals(value) != true)) {
                    this.EmployeeRoleField = value;
                    this.RaisePropertyChanged("EmployeeRole");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IHeadSpringService")]
    public interface IHeadSpringService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeadSpringService/GetEmployee", ReplyAction="http://tempuri.org/IHeadSpringService/GetEmployeeResponse")]
        System.Data.DataSet GetEmployee(string EmployeeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeadSpringService/DeleteEmployee", ReplyAction="http://tempuri.org/IHeadSpringService/DeleteEmployeeResponse")]
        System.Data.DataSet DeleteEmployee(System.Data.DataSet deleteEmployees);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeadSpringService/AddEmployee", ReplyAction="http://tempuri.org/IHeadSpringService/AddEmployeeResponse")]
        System.Data.DataSet AddEmployee(System.Data.DataSet addEmployees);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeadSpringService/UpdateEmployee", ReplyAction="http://tempuri.org/IHeadSpringService/UpdateEmployeeResponse")]
        System.Data.DataSet UpdateEmployee(System.Data.DataSet updateEmployees);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeadSpringService/EmployeeLogin", ReplyAction="http://tempuri.org/IHeadSpringService/EmployeeLoginResponse")]
        HeadSpringApp.ServiceReference1.Employee[] EmployeeLogin(string LoginName, string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHeadSpringServiceChannel : HeadSpringApp.ServiceReference1.IHeadSpringService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HeadSpringServiceClient : System.ServiceModel.ClientBase<HeadSpringApp.ServiceReference1.IHeadSpringService>, HeadSpringApp.ServiceReference1.IHeadSpringService {
        
        public HeadSpringServiceClient() {
        }
        
        public HeadSpringServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HeadSpringServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HeadSpringServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HeadSpringServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetEmployee(string EmployeeName) {
            return base.Channel.GetEmployee(EmployeeName);
        }
        
        public System.Data.DataSet DeleteEmployee(System.Data.DataSet deleteEmployees) {
            return base.Channel.DeleteEmployee(deleteEmployees);
        }
        
        public System.Data.DataSet AddEmployee(System.Data.DataSet addEmployees) {
            return base.Channel.AddEmployee(addEmployees);
        }
        
        public System.Data.DataSet UpdateEmployee(System.Data.DataSet updateEmployees) {
            return base.Channel.UpdateEmployee(updateEmployees);
        }
        
        public HeadSpringApp.ServiceReference1.Employee[] EmployeeLogin(string LoginName, string Password) {
            return base.Channel.EmployeeLogin(LoginName, Password);
        }
    }
}
