//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeadSpringApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/HeadSpringWcf")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeJobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeePhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeEmail {
            get {
                return this.EmployeeEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeEmailField, value) != true)) {
                    this.EmployeeEmailField = value;
                    this.RaisePropertyChanged("EmployeeEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeJobTitle {
            get {
                return this.EmployeeJobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeJobTitleField, value) != true)) {
                    this.EmployeeJobTitleField = value;
                    this.RaisePropertyChanged("EmployeeJobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeLocation {
            get {
                return this.EmployeeLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeLocationField, value) != true)) {
                    this.EmployeeLocationField = value;
                    this.RaisePropertyChanged("EmployeeLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeName {
            get {
                return this.EmployeeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeNameField, value) != true)) {
                    this.EmployeeNameField = value;
                    this.RaisePropertyChanged("EmployeeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeePhoneNumber {
            get {
                return this.EmployeePhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeePhoneNumberField, value) != true)) {
                    this.EmployeePhoneNumberField = value;
                    this.RaisePropertyChanged("EmployeePhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IHeadSpringService")]
    public interface IHeadSpringService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeadSpringService/GetEmployee", ReplyAction="http://tempuri.org/IHeadSpringService/GetEmployeeResponse")]
        HeadSpringApp.ServiceReference1.Employee[] GetEmployee(HeadSpringApp.ServiceReference1.Employee[] getEmployeeList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeadSpringService/DeleteEmployee", ReplyAction="http://tempuri.org/IHeadSpringService/DeleteEmployeeResponse")]
        void DeleteEmployee(HeadSpringApp.ServiceReference1.Employee[] deleteEmployees);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeadSpringService/AddEmployee", ReplyAction="http://tempuri.org/IHeadSpringService/AddEmployeeResponse")]
        void AddEmployee(HeadSpringApp.ServiceReference1.Employee[] addEmployees);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeadSpringService/UpdateEmployee", ReplyAction="http://tempuri.org/IHeadSpringService/UpdateEmployeeResponse")]
        void UpdateEmployee(HeadSpringApp.ServiceReference1.Employee[] updateEmployees);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHeadSpringServiceChannel : HeadSpringApp.ServiceReference1.IHeadSpringService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HeadSpringServiceClient : System.ServiceModel.ClientBase<HeadSpringApp.ServiceReference1.IHeadSpringService>, HeadSpringApp.ServiceReference1.IHeadSpringService {
        
        public HeadSpringServiceClient() {
        }
        
        public HeadSpringServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HeadSpringServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HeadSpringServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HeadSpringServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HeadSpringApp.ServiceReference1.Employee[] GetEmployee(HeadSpringApp.ServiceReference1.Employee[] getEmployeeList) {
            return base.Channel.GetEmployee(getEmployeeList);
        }
        
        public void DeleteEmployee(HeadSpringApp.ServiceReference1.Employee[] deleteEmployees) {
            base.Channel.DeleteEmployee(deleteEmployees);
        }
        
        public void AddEmployee(HeadSpringApp.ServiceReference1.Employee[] addEmployees) {
            base.Channel.AddEmployee(addEmployees);
        }
        
        public void UpdateEmployee(HeadSpringApp.ServiceReference1.Employee[] updateEmployees) {
            base.Channel.UpdateEmployee(updateEmployees);
        }
    }
}
